# Generated by Django 4.2.3 on 2026-01-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_rename_question_question_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='gradepoint',
            new_name='grade',
        ),
    ]
